// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rocnikovka_first.Data;

#nullable disable

namespace Rocnikovka_first.Migrations
{
    [DbContext(typeof(RocnikovkaContext))]
    partial class RocnikovkaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rocnikovka.Models.Excuse", b =>
                {
                    b.Property<int>("Excuse_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Excuse_ID"));

                    b.Property<string>("Excuse_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Excuse_ID");

                    b.HasIndex("Member_ID");

                    b.ToTable("Excuses");
                });

            modelBuilder.Entity("Rocnikovka.Models.Member", b =>
                {
                    b.Property<int>("Member_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Member_ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Birth_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_of_birth")
                        .HasColumnType("DATE");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Health_insurance_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Health_insurance_number")
                        .HasColumnType("int");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_ID")
                        .HasColumnType("int");

                    b.Property<int>("Team_ID")
                        .HasColumnType("int");

                    b.HasKey("Member_ID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("Team_ID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Rocnikovka.Models.Representative", b =>
                {
                    b.Property<int>("Representative_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Representative_ID"));

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Telephone")
                        .HasColumnType("int");

                    b.HasKey("Representative_ID");

                    b.HasIndex("Member_ID");

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("Rocnikovka.Models.Residence", b =>
                {
                    b.Property<int>("Residence_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Residence_ID"));

                    b.Property<string>("City_part")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<int>("PSC")
                        .HasColumnType("int");

                    b.Property<string>("Postal_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Residence_ID");

                    b.HasIndex("Member_ID");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Rocnikovka.Models.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Rocnikovka.Models.Team", b =>
                {
                    b.Property<int>("Team_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Team_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Team_ID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Rocnikovka.Models.Training", b =>
                {
                    b.Property<int>("Training_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Training_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<TimeOnly>("End_time")
                        .HasColumnType("TIME");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Start_time")
                        .HasColumnType("TIME");

                    b.HasKey("Training_ID");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Rocnikovka.Models.Excuse", b =>
                {
                    b.HasOne("Rocnikovka.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Member_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Rocnikovka.Models.Member", b =>
                {
                    b.HasOne("Rocnikovka.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rocnikovka.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("Team_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Rocnikovka.Models.Representative", b =>
                {
                    b.HasOne("Rocnikovka.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Member_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Rocnikovka.Models.Residence", b =>
                {
                    b.HasOne("Rocnikovka.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("Member_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
