// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rocnikovka_first.Data;

#nullable disable

namespace Rocnikovka_first.Migrations
{
    [DbContext(typeof(RocnikovkaContext))]
    partial class RocnikovkaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rocnikovka_first.Models.Attendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("personId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("trainingId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int>("birth_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("DATE");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("health_insurance_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("health_insurance_number")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<int>("teamId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("roleId");

                    b.HasIndex("teamId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Representative", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personId")
                        .HasColumnType("int");

                    b.Property<int?>("telephone")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("personId");

                    b.ToTable("Representative");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Residence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city_part")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personId")
                        .HasColumnType("int");

                    b.Property<string>("postal_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("psc")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("personId");

                    b.ToTable("Residence");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Training", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("DATE");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("TIME");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("TIME");

                    b.HasKey("id");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Person", b =>
                {
                    b.HasOne("Rocnikovka_first.Models.Role", "role")
                        .WithMany("people")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rocnikovka_first.Models.Team", "team")
                        .WithMany("members")
                        .HasForeignKey("teamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("team");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Representative", b =>
                {
                    b.HasOne("Rocnikovka_first.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Residence", b =>
                {
                    b.HasOne("Rocnikovka_first.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("personId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Role", b =>
                {
                    b.Navigation("people");
                });

            modelBuilder.Entity("Rocnikovka_first.Models.Team", b =>
                {
                    b.Navigation("members");
                });
#pragma warning restore 612, 618
        }
    }
}
